# Generated by Django 5.2.1 on 2025-06-26 22:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('fiat', 'Fiat'), ('crypto', 'Cryptocurrency'), ('token', 'Token')], max_length=10)),
                ('network', models.CharField(choices=[('mainnet', 'Mainnet'), ('testnet', 'Testnet')], default='mainnet', max_length=10)),
                ('contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('min_withdrawal', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('min_deposit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('withdrawal_fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('withdrawal_fee_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percentage')], default='fixed', max_length=10)),
                ('deposit_enabled', models.BooleanField(default=True)),
                ('withdrawal_enabled', models.BooleanField(default=True)),
                ('trading_enabled', models.BooleanField(default=True)),
                ('precision', models.PositiveSmallIntegerField(default=8)),
                ('confirmations_required', models.PositiveSmallIntegerField(default=6)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'indexes': [models.Index(fields=['code', 'is_active'], name='wallet_curr_code_0101ab_idx'), models.Index(fields=['type', 'is_active'], name='wallet_curr_type_9ce5a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('locked', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('staked', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('interest_owed', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('fee', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('trade', 'Trade'), ('staking', 'Staking'), ('earning', 'Earning'), ('fee', 'Fee'), ('rebate', 'Rebate'), ('adjustment', 'Adjustment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('rejected', 'Rejected'), ('processing', 'Processing')], default='pending', max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('txid', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmations', models.PositiveIntegerField(default=0)),
                ('required_confirmations', models.PositiveIntegerField(default=6)),
                ('network', models.CharField(blank=True, max_length=50, null=True)),
                ('from_address', models.CharField(blank=True, max_length=255, null=True)),
                ('to_address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.currency')),
                ('fee_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_transactions', to='wallet.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('24h', '24 Hours'), ('7d', '7 Days'), ('30d', '30 Days')], default='24h', max_length=5)),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Tier 1 - Basic'), (2, 'Tier 2 - Verified'), (3, 'Tier 3 - Enhanced'), (4, 'Tier 4 - Institutional')], default=1)),
                ('limit_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('used_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('remaining_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reset_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_limits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('privkey', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('derivation_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Deposit Addresses',
                'indexes': [models.Index(fields=['user', 'currency'], name='wallet_depo_user_id_7b44a2_idx'), models.Index(fields=['address'], name='wallet_depo_address_3ac6c8_idx')],
                'unique_together': {('user', 'currency', 'address', 'memo')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('rate_type', models.CharField(choices=[('spot', 'Spot'), ('future', 'Future'), ('margin', 'Margin')], default='spot', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='internal', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='wallet.currency')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_rates', to='wallet.currency')),
            ],
            options={
                'indexes': [models.Index(fields=['base_currency', 'quote_currency'], name='wallet_exch_base_cu_9ef692_idx')],
                'unique_together': {('base_currency', 'quote_currency', 'rate_type')},
            },
        ),
        migrations.CreateModel(
            name='NetworkFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=50)),
                ('withdrawal_fee', models.DecimalField(decimal_places=8, max_digits=20)),
                ('withdrawal_min', models.DecimalField(decimal_places=8, max_digits=20)),
                ('deposit_enabled', models.BooleanField(default=True)),
                ('withdrawal_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.currency')),
            ],
            options={
                'verbose_name_plural': 'Network Fees',
                'unique_together': {('currency', 'network')},
            },
        ),
        migrations.CreateModel(
            name='UserAddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('address_type', models.CharField(choices=[('external', 'External Wallet'), ('internal', 'Internal Transfer')], default='external', max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_book', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Address Book',
                'unique_together': {('user', 'currency', 'address', 'memo')},
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user', 'currency'], name='wallet_wall_user_id_d9a39b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'currency')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='wallet_tran_user_id_9b1f68_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['txid'], name='wallet_tran_txid_f51749_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='wallet_tran_created_fb97c1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['currency', 'type'], name='wallet_tran_currenc_b1d245_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawallimit',
            index=models.Index(fields=['user', 'currency'], name='wallet_with_user_id_e6be77_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='withdrawallimit',
            unique_together={('user', 'currency', 'period')},
        ),
    ]
